MACHINE ??= 'imx6qrsb4411a1'
DISTRO ?= 'fsl-imx-x11'
UBOOT_CONFIG ?= '1G'
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
USER_CLASSES ?= "buildstats"
PATCHRESOLVE = "noop"
BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    HALT,${TMPDIR},100M,1K \
    HALT,${DL_DIR},100M,1K \
    HALT,${SSTATE_DIR},100M,1K \
    HALT,/tmp,10M,1K"
PACKAGECONFIG:append:pn-qemu-system-native = " sdl"
CONF_VERSION = "2"

DL_DIR ?= "${BSPDIR}/downloads/"
ACCEPT_FSL_EULA = "1"

## YoctianOS
PACKAGE_CLASSES = "package_deb"
EXTRA_IMAGE_FEATURES += " package-management "

IMAGE_INSTALL:append = "\
    yoctianos-system \
    yoctianos-firstboot \
    yoctianos-arm-none-eabi \
    apt \
    sudo \
    systemd \
    openssh-sshd \
    gnupg \
    git \
    wget \
    curl \
    unzip \
    dfu-util \
    xserver-xorg \
    xinit \
    xinput \
    gobject-introspection \
    gobject-introspection-dev \
    cairo \
    cairo-dev \
    pkgconfig \
    gtk+3 \
    gtk+3-dev \
    librsvg \
    openjpeg \
    dbus-glib \
    dbus-glib-dev \
    autoconf \
    mpv \
    mpv-dev \
    ffmpeg \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    xf86-input-evdev \
    xf86-input-libinput \
    xf86-video-fbdev \
    gcc \
    libffi \
    libffi-dev \
    packagegroup-core-buildessential \
    ncurses \
    ncurses-dev \
    libusb1 \
    libusb1-dev \
    avrdude \
    avr-gcc \
    avr-binutils \
    avr-libc \
    stm32flash \
    libsodium \
    libsodium-dev \
    zlib \
    zlib-dev \
    jpeg \
    wireless-tools \
    iw \
    packagekit \
"

#IMAGE_INSTALL:remove = " "

VIRTUAL-RUNTIME_init = "systemd"

LICENSE_FLAGS_ACCEPTED += "commercial"
