MEMORY_REQUIRED="\
    yoctianos-system \
    yoctianos-firstboot \
    yoctianos-arm-none-eabi \
    yoctianos-klipper-addon \
    apt \
    sudo \
    systemd \
    openssh \
    gnupg \
    git \
    wget \
    curl \
    unzip \
    dfu-util \
    xserver-xorg \
    xinit \
    xinput \
    gobject-introspection \
    cairo \
    pkgconfig \
    gtk+3 \
    librsvg \
    openjpeg \
    dbus-glib \
    autoconf \
    mpv \
    ffmpeg \
    python3 \
    python3-pip \
    xf86-input-evdev \
    xf86-input-libinput \
    xf86-video-fbdev \
    gcc \
    libffi \
    packagegroup-core-buildessential \
    ncurses \
    libusb1 \
    avrdude \
    avr-gcc \
    avr-binutils \
    avr-libc \
    stm32flash \
    libsodium \
    zlib \
    jpeg \
    wireless-tools \
    iw \
    tzdata \
"
MEMORY_RECOMMENDED="htop screen"
MEMORY_OPTIONAL=""
