# Layer root
LAYERDIR := "${@os.path.normpath(os.path.dirname(d.getVar('FILE', True)) + '/..')}"

# Add the layer root to BBPATH
BBPATH .= ":${LAYERDIR}"

# Layer metadata
LAYERVERSION = "1"

# Collection and pattern (match the entire layer)
BBFILE_COLLECTIONS += "meta-yoctianos-advantech"
BBFILE_PATTERN_meta-yoctianos-advantech := "^${LAYERDIR}/"

# Dependencies and priority
LAYERDEPENDS_meta-yoctianos-advantech = "core"
BBFILE_PRIORITY_meta-yoctianos-advantech = "99"

# Yocto compatibility
LAYERSERIES_COMPAT_meta-yoctianos-advantech = "mickledore"

# Special Fixes for Meta Microcontroller
LAYERSERIES_COMPAT_meta-microcontroller += "mickledore "

PREMIRRORS:prepend = "\
    ftp://ftp.gnu.org/pub/gnu/ https://mirrors.ocf.berkeley.edu/gnu/ \n \
    http://ftp.gnu.org/pub/gnu/ https://mirrors.ocf.berkeley.edu/gnu/ \n \
    https://ftp.gnu.org/pub/gnu/ https://mirrors.ocf.berkeley.edu/gnu/ \n \
"
