# Layer root (normalized)
LAYERDIR := "${@os.path.normpath(os.path.dirname(d.getVar('FILE', True)) + '/..')}"

# Add the layer root to BBPATH
BBPATH .= ":${LAYERDIR}"

# Layer metadata
LAYERVERSION = "1"

# Collection and pattern (match the entire layer)
BBFILE_COLLECTIONS += "meta-yoctianos"
BBFILE_PATTERN_meta-yoctianos := "^${LAYERDIR}/"

# Dependencies and priority
LAYERDEPENDS_meta-yoctianos = "core"
BBFILE_PRIORITY_meta-yoctianos = "6"

# Yocto compatibility
LAYERSERIES_COMPAT_meta-yoctianos = "mickledore"
